name: Create Release

concurrency:
  group: create-release

on:
  pull_request_target:
    types:
      - closed
    branches:
      - main


jobs:
  create_release:
    uses: afeick/reusable-github-actions/.github/workflows/create_release.yml@main
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
